# Generated by Django 5.0.1 on 2024-01-27 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('rfid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('accountno', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('rfid', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('balance', models.IntegerField(default=0)),
                ('rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rec', to='Banking.user')),
                ('send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send', to='Banking.user')),
            ],
        ),
    ]
