# Generated by Django 5.0.1 on 2024-03-07 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Banking', '0002_user_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='post',
            new_name='type',
        ),
    ]
