# Generated by Django 5.0.1 on 2024-03-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banking', '0003_rename_post_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tag',
            field=models.CharField(default='hehe', max_length=10),
        ),
    ]
