# Generated by Django 5.0.1 on 2024-03-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banking', '0004_user_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='status',
            field=models.CharField(default='Processing', max_length=20),
        ),
    ]
