# Generated by Django 5.0.1 on 2024-03-08 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Banking', '0005_transactions_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='status',
        ),
    ]
